"""initial_schema

Revision ID: c01829b599bc
Revises: 
Create Date: 2026-09-09 19:17:27.041537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c01829b599bc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('usuario_github', sa.String(length=100), nullable=True),
    sa.Column('usuario_gitlab', sa.String(length=100), nullable=True),
    sa.Column('perfil_linkedin', sa.String(length=255), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni', name='uq_alumnos_dni'),
    sa.UniqueConstraint('email', name='uq_alumnos_email')
    )
    op.create_index(op.f('ix_alumnos_dni'), 'alumnos', ['dni'], unique=True)
    op.create_index(op.f('ix_alumnos_email'), 'alumnos', ['email'], unique=True)
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('cupos', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', name='uq_cursos_nombre')
    )
    op.create_index(op.f('ix_cursos_nombre'), 'cursos', ['nombre'], unique=True)
    op.create_table('inscripciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inscripcion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('estado', sa.Enum('ACTIVA', 'BAJA', name='estadoinscripcion', native_enum=False, length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alumno_id', 'curso_id', name='uq_inscripciones_alumno_curso')
    )
    op.create_index('ix_inscripciones_alumno_curso_activa', 'inscripciones', ['alumno_id', 'curso_id'], unique=True, postgresql_where=sa.text("estado = 'activa'"))
    op.create_index(op.f('ix_inscripciones_alumno_id'), 'inscripciones', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_inscripciones_curso_id'), 'inscripciones', ['curso_id'], unique=False)
    op.create_table('materias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materias_curso_id'), 'materias', ['curso_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'DOCENTE', 'ALUMNO', name='rolusuario', native_enum=False, length=10), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_usuarios_email'),
    sa.UniqueConstraint('username', name='uq_usuarios_username')
    )
    op.create_index(op.f('ix_usuarios_alumno_id'), 'usuarios', ['alumno_id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_table('asignaciones_docente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'curso_id', name='uq_asignacion_docente_usuario_curso')
    )
    op.create_index(op.f('ix_asignaciones_docente_curso_id'), 'asignaciones_docente', ['curso_id'], unique=False)
    op.create_index(op.f('ix_asignaciones_docente_usuario_id'), 'asignaciones_docente', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_asignaciones_docente_usuario_id'), table_name='asignaciones_docente')
    op.drop_index(op.f('ix_asignaciones_docente_curso_id'), table_name='asignaciones_docente')
    op.drop_table('asignaciones_docente')
    op.drop_index(op.f('ix_usuarios_username'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_alumno_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_materias_curso_id'), table_name='materias')
    op.drop_table('materias')
    op.drop_index(op.f('ix_inscripciones_curso_id'), table_name='inscripciones')
    op.drop_index(op.f('ix_inscripciones_alumno_id'), table_name='inscripciones')
    op.drop_index('ix_inscripciones_alumno_curso_activa', table_name='inscripciones', postgresql_where=sa.text("estado = 'activa'"))
    op.drop_table('inscripciones')
    op.drop_index(op.f('ix_cursos_nombre'), table_name='cursos')
    op.drop_table('cursos')
    op.drop_index(op.f('ix_alumnos_email'), table_name='alumnos')
    op.drop_index(op.f('ix_alumnos_dni'), table_name='alumnos')
    op.drop_table('alumnos')
    # ### end Alembic commands ###