"""remove_full_unique_constraint_inscripciones

Revision ID: 68fcdc9a6d41
Revises: c01829b599bc
Create Date: 2026-09-10 06:48:34.626272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '68fcdc9a6d41'
down_revision: Union[str, None] = 'c01829b599bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_inscripciones_alumno_curso', 'inscripciones', type_='unique')
    op.add_column('materias', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('materias', sa.Column('updated_by', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('materias', 'updated_by')
    op.drop_column('materias', 'created_by')
    op.create_unique_constraint('uq_inscripciones_alumno_curso', 'inscripciones', ['alumno_id', 'curso_id'])
    # ### end Alembic commands ###